config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'
  get 'chats/to_message'

  # RESTfulなURLを自動生成してくれるresources

  #基本ページ系のルーティング
  root to: 'home#top_page'
  resource :home, path: '',  only: [] do
    get 'welcome' => 'home#welcome', as: 'welcome'
    get 'my_page' => 'home#index',  as: 'my_page'
    get 'top_page' => 'home#top_page', as: 'top_page'
    get 'contact_list' => 'home#contact_list', as: 'contact_list'
    get 'tutorial' => 'home#tutorial', as: 'tutorial'
  end


  #user系のルーティング
  resources :members
  resources :events
  post 'events/add_member' => 'events#add_member', as: 'event_add_member'


  #member_messageのルーティング
  resources :member_messages


  #deviseのroutes設定
  devise_for :members, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }, controllers: {
    # membersのomniauth_callbackというコントローラにルーティングします
    omniauth_callbacks: "members/omniauth_callbacks"}

  #community系のルーティング
  resources :communities, except: [:add_member] do
  end
  post 'communities/add_member' => 'communities#add_member', as: 'community_add_member'
  #シャッフルコミュニティの生成
  get 'set_shuffle' => 'communities#set_shuffle', as: 'community_set_shuffle'
  post 'shuffle_community' => 'communities#shuffle_community', as: 'community_shuffle_communityr'

  resources :community_comments

  #about rejobook_news routing
  resources :news, controller: :rejobook_news
  post "news/create_news_comment" => 'rejobook_news#create_news_comment', as: 'create_news_comment'
  #get '*path', controller: 'application', action: 'render_404'

  #admin管理画面用のルーティング
  resource :admin_users, only: [] do
    get  'member_index',  to: 'admin_users#member_index'
    get  'community_index',  to: 'admin_users#community_index'
    get  'message_index',  to: 'admin_users#message_index'
    get  'news_index',  to: 'admin_users#news_index'
    get  'index',  to: 'admin_users#index'
  end

  #お問い合わせ用ルーティング
  get 'contact', to: 'contacts#contact'
  post 'contact/post_contact', to: 'contacts#post_contact'

  #resources :articles
  get 'articles/all_index'
  get 'articles/facebook_index'
  get 'articles/show'

  get 'news/delete_comment/:comment_id/:news_id' => 'rejobook_news#delete_comment'




=begin
  #thank_buttonのためのルーティング
  resources :thanks, only: []
  get 'members/:id/thanks/:from_member_id/thank_create' => 'thanks#thank_create'
=end

=begin
  devise_for :members, path: 'member', except: [:session] do
    get 'login', to: 'devise/sessions#new', as:  'login'
    post 'login', to: 'devise/sessions#create', as:  'login'
    match 'logout', to: 'devise/sessions#destroy', as:  'logout',
    controllers: {
    # membersのomniauth_callbackというコントローラにルーティングします
      omniauth_callbacks: "members/omniauth_callbacks"
    }
  end
=end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login!, except: [:welcome]
  after_action :sign_in_count!, only: [:tutorial]
  before_action :null_check!, only: [:top_page]
  before_action :nil_session?, only: [:top_page]
  before_action :set_count_session, only: [:top_page]
  before_action :home_session_check!, only: [:top_page]
  after_action :null_check_blank!, only: [:top_page]


  def index
    @members = Member.latest_member
    @communities = Community.latest_community
    if params[:q].nil?
      @search = Member.none.search
      @results = {}
    else
      @search = Member.search(params[:q])
      @results = @search.result(distinct: true)
    end
    if Community.count > 3
      @random_communities = Community.find(Community.pluck(:id).sample(3))
    else
      @random_communities = Community.all
    end
    if MemberMessage.count > 11
      @member_messages = MemberMessage.find(MemberMessage.pluck(:id).sample(10))
    else
      @member_messages = MemberMessage.find(MemberMessage.pluck(:id).sample(MemberMessage.count))
    end
    @rejobook_news = News.available
  end

  def welcome
  end

  def sample
    @rejobook_news = News.available
    if params[:q].nil?
      @search = Member.none.search
      @results = {}
    else
      @search = Member.search(params[:q])
      @results = @search.result(distinct: true)
    end
  end

  def top_page
    @rejobook_news = News.available
    if params[:q].nil?
      @search = Member.none.search
      @results = {}
    else
      @search = Member.search(params[:q])
      @results = @search.result(distinct: true)
    end
  end

  def contact_list
    if params[:q].nil?
      @search = Member.all.search
      @results = Member.all.page(params[:page]).per(40)
    else
      @search = Member.search(params[:q])
      @results = @search.result(distinct: true).page(params[:page]).per(40)
    end
  end

  def tutorial
  end

  private

  def null_check!
    flash[:error] = '入力されていないデータがあります' if current_member.data_null?
  end

  def null_check_blank!
    flash[:error] = nil
  end

  def sign_in_count!
    if current_member.sign_in_count <= 1
      current_member.sign_in_count += 1
      current_member.save
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact_list.html.erb
<%= render template: 'layouts/_nav_bar' %>

<div class="container">

<!--検索ボックス-->
  <div class="panel panel-default panel-body panel-head">
    <div class="row">
      <%= search_form_for @search, url: contact_list_home_path(params[:q]) do |f| %>

      <div class="form-group col-md-6 col-xs-6">
        <%= f.label :name_or_kana_cont, '名前', class: "control-label" %>
        <br>
        <% if params[:q].present? %>
        <% if params[:q][:name_or_kana_cont].present? %>
        <%= f.search_field :name_or_kana_cont, :placeholder => "#{params[:q][:name_or_kana_cont]}", rows: "3" %>
        <% else %>
        <%= f.search_field :name_or_kana_cont, class: "search_name", placeholder: "検索する名前を入力してください", rows: "3" %>
        <% end %>
        <% else %>
        <%= f.search_field :name_or_kana_cont, class: "search_name", placeholder: "検索する名前を入力してください", rows: "3" %>
        <% end %>
      </div>
      <div class="form-group col-md-6 col-xs-6">
        <div class="checkbox">
          <label>
            <%= f.label :department, '所属部署' %>
            <br>
            <% if params[:q].present? %>
            <% if params[:q][:departments_id_in].present? %>
            <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :selected => params[:q][:departments_id_in], :include_blank => true %>
            <% else %>
            <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :prompt => "部署を選択してください" %>
            <% end %>
            <% else %>
            <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :prompt => "部署を選択してください" %>
            <% end %>
          </label>
        </div>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: -15px; text-align: center">
      <%= f.submit "検索", class: "btn btn-material-pink" %>
      <br>
    </div>
    <% end %>
  </div>

<!--ここに検索結果をだす→テーブルで-->
    <h4 class="result">検索結果</h4>
    <div class="panel panel-default">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>No</th>
            <th>名前</th>
            <th>チャットワークid</th>
            <th>内線番号</th>
          </tr>
        </thead>
        <tbody>
          <% @results.each_with_index do |result, idx| %>
          <% if idx % 2 == 0 %>
          <tr class="success">
            <% else %>
            <tr>
              <% end %>
              <td style="text-align: center"><%= result.id %></td>
              <td style="text-align: center"><%= result.name %></td>
              <td style="text-align: center"><%= result. chatwork_id%></td>
              <td style="text-align: center"><%= result.indoor_call %></td>
              <td style="text-align: center"><%= link_to '詳細', member_path(result.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <style media="screen">
      th {
        text-align: center;
      }
    </style>

app/views/home/sample.html.erb
<body>
  <div class="container">
    <div class="logo">
      <img alt="" src="images/rejoßook.png" width="60%" height="20%"/>
    </div>

    <%= search_form_for @search, url: contact_list_home_path(params[:q]) do |f| %>
      <div class="searchitem">
        <div class="form-group">
          <%= f.label :name_cont, '名前', class: "control-label" %>
          <% if params[:q].present? %>
          <% if params[:q][:name_cont].present? %>
          <%= f.search_field :name_cont, :placeholder => "#{params[:q][:name_cont]}", class: "form-control", rows: "3" %>
          <% else %>
          <%= f.search_field :name_cont, class: "form-control", rows: "3" %>
          <% end %>
          <% else %>
          <%= f.search_field :name_cont, class: "form-control", rows: "3" %>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :department, '所属部署' %>
          <% if params[:q].present? %>
          <% if params[:q][:departments_id_in].present? %>
          <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :selected => params[:q][:departments_id_in], :include_blank => true %>
          <% else %>
          <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :prompt => "部署を選択してください" %>
          <% end %>
          <% else %>
          <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :prompt => "部署を選択してください" %>
          <% end %>
        </div>
      </div>

      <div class="form-group search">
        <%= f.submit "検索", class: "btn btn-flat btn-material-pink" %>
      </div>
      <% end %>

      <div class="navi">
        <ul>
          <li style="float: left">
            <a href="http://localhost:3000/members">
            <i class="mdi-social-person"><span class="badge"><%= session[:member_count] %></span></i>
            <br>社員一覧
            </a>
          </li>
          <li style="float: left">
            <a href="http://localhost:3000/communities">
            <i class="mdi-social-people"><span class="badge"><%= session[:community_count] %></span></i>
            <br>コミュニティ一覧
            </a>
          </li>
          <li style="float: left">
            <a href="http://localhost:3000/chats/index">
            <i class="mdi-social-mood"><span class="badge"><%= session[:chat_count] %></span></i>
            <br>みんなのメッセージ
          </a>
          </li>
          <li style="float: left">
            <a href="http://localhost:3000/news">
            <i class="mdi-av-my-library-books"><span class="badge"><%= session[:news_count] %></span></i>
            <br>ニュース一覧
            </a>
          </li>
        </ul>
        <div style="clear: both"></div>
      </div>

    <div class="newstelp">
      <ul id="sample2" class="text" style="list-style-type: none;">
        <% @rejobook_news.reverse_each do |news|  %>
        <li>
          [<%= news.department.name %>]<%= link_to "#{news.title}", news_path(news.id) %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</body>

<script type="text/javascript">
$.fn.autoChange = function(config) {
   // オプション
   var options = $.extend({
      effect  : 'fade',
      type    : 'repaet',
      timeout : 3000,
      speed   : 1000
   }, config);

   return this.each(function() {
      // カウンター初期化
      var current = 0;
      var next = 1;

      // 指定した要素の子要素を取得
      var element = $(this).children();

      // 全ての要素を非表示にする
      $(element).hide();

      // 最初の要素だけ表示する
      $(element[0]).show();

      // 要素を切り替えるスクリプト
      var change = function(){
         // フェードしながら切り替える場合
         if (options.effect == 'fade') {
            $(element[current]).fadeOut(options.speed);
            $(element[next]).fadeIn(options.speed);

         // スライドしながら切り替える場合
         } else if  (options.effect == 'slide') {
            $(element[current]).slideUp(options.speed);
            $(element[next]).slideDown(options.speed);
         }

         // リピートする場合
         if (options.type == 'repeat') {
            if ((next + 1) < element.length) {
                current = next;
                next++;
            } else {
                current = element.length - 1;
                next = 0;
            }
         }

         // 最後の要素でストップする場合
         if (options.type == 'stop') {
            if ((next + 1) < element.length) {
                current = next;
                next++;
            } else {
                return;
            }
         }
      };

      // 設定時間毎にスクリプトを実行
      var timer = setInterval(function(){change();}, options.timeout);
   });
};


// 自動切り替えする要素の設定
$(function() {
   $('#sample1').autoChange({effect : 'fade', type : 'stop', timeout: 3000, speed : 1000});
   $('#sample2').autoChange({effect : 'fade', type : 'repeat', timeout: 3000, speed : 1000});
   $('#sample3').autoChange({effect : 'slide', type : 'repeat', timeout: 3000, speed : 1000});
   $('#sample4').autoChange({effect : 'slide', type : 'stop', timeout: 3000, speed : 1000});
});

</script>

app/views/home/top_page.html.erb
<%= render template: 'layouts/_nav_bar' %>

<body>

  <div class="container">
<!--top_page-->
    <div class="logo">
      <img alt="" height="20%" src="images/rejoßook.png" width="60%"/>
    </div>

    <%= search_form_for @search, url: contact_list_home_path(params[:q]) do |f| %>
    <div class="searchitem row">
      <div class="form-group col-md-6 col-xs-6">
        <%= f.label :name_or_kana_cont, '名前', class: "control-label" %>
        <% if params[:q].present? %>
        <% if params[:q][:name_or_kana_cont].present? %>
        <%= f.search_field :name_or_kana_cont, :placeholder => "#{params[:q][:name_or_kana_cont]}", rows: "3" %>
        <% else %>
        <%= f.search_field :name_or_kana_cont, class: "search_name", placeholder: "検索する名前を入力してください", rows: "3" %>
        <% end %>
        <% else %>
        <%= f.search_field :name_or_kana_cont, class: "search_name", placeholder: "検索する名前を入力してください", rows: "3" %>
        <% end %>
      </div>
      <div class="form-group col-md-6 col-xs-6" style="text-align: center">
        <%= f.label :department, '所属部署' %>
        <br>
        <% if params[:q].present? %>
        <% if params[:q][:departments_id_in].present? %>
        <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :selected => params[:q][:departments_id_in], :include_blank => true %>
        <% else %>
        <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :prompt => "部署を選択してください" %>
        <% end %>
        <% else %>
        <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :prompt => "部署を選択してください" %>
        <% end %>
      </div>
    </div>

    <div class="form-group search">
      <%= f.submit "連絡先を取得", class: "btn btn-material-pink"%>
    </div>
    <% end %>

  </div>

</body>

app/views/home/tutorial.html.erb
<%= render template: 'layouts/_nav_bar' %>


<div class="container" style="margin-top: 5%; z-index: 2;">
  <div class="panel panel-default">
<!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li class="active" role="presentation">
        <a aria-controls="home" data-toggle="tab" href="#home" role="tab">はじめに</a>
      </li>
      <% if current_member.sign_in_count > 1 %>
      <li role="presentation">
        <a aria-controls="profile" data-toggle="tab" href="#profile" role="tab">社員の情報を取得する</a>
      </li>
      <li role="presentation">
        <a aria-controls="messages" data-toggle="tab" href="#messages" role="tab">REJOBのコミュニティを見る</a>
      </li>
      <li role="presentation">
        <a aria-controls="settings" data-toggle="tab" href="#settings" role="tab">REJOBのイベントに参加する</a>
      </li>
      <% end %>
    </ul>

<!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane active" id="home" role="tabpanel">
        <h4>REJOBOOKは、リジョブの"人"をもっと知れる場所！</h4>
        <br>
        <img alt="" src="http://pictogram2.com/p/p0663/1.jpg"/ width="100px" height="100px">
        あの社員と連絡をとりたいけど、チャットワークや内線番号がわからない…
        <br>
        <img alt="" src="http://pictogram2.com/p/p0662/1.jpg"/ width="100px" height="100px">
        よく業務で関わるあの部署の社員さんの名前を知りたいな…
        <br>
        <img alt="" src="http://pictogram2.com/p/p0227/6.png"/ width="100px" height="100px">
        リジョブの人と話す機会があるといいな…
        <br>
        <h4>リジョブの"人"をもっと知れる、Rejobookはそのきっかけになるサービスです</h4>
        <% if current_member.sign_in_count == 1 %>
        <a aria-controls="profile" class="btn btn-material-pink" data-toggle="tab" href="#profile" role="tab">次へ</a>
        <% end %>
      </div>
      <div class="tab-pane" id="profile" role="tabpanel">
        <h4>社員の名前や所属部署、業務内容、連絡先から、誕生日や趣味までわかる！</h4>
        <br>
        <img alt="" src="http://pictogram2.com/p/p0663/1.jpg"/ width="100px" height="100px">
        どうやって検索できるの？
        <br>
        1)トップページの検索ボックスから社員情報を取得する
        <br>
        2)社員一覧から社員情報を取得する
        <br>
        <% if current_member.sign_in_count == 1 %>
        <a aria-controls="messages" class="btn btn-material-pink" data-toggle="tab" href="#messages" role="tab">次へ</a>
        <% else %>
        <%= link_to '社員を見に行く', members_path, class:"btn btn-material-pink" %>
        <% end %>
      </div>
      <div class="tab-pane" id="messages" role="tabpanel">
        <h4>REJOBのコミュニティに行ってみよう！</h4>
        <br>
        <img alt="" src="http://pictogram2.com/p/p0663/1.jpg"/ width="100px" height="100px">
        共通の趣味がある人はいないかな？
        <br>
        コミュニティ一覧で自分に合うコミュニティを探すことができる！
        <br>
        <img alt="" src="http://pictogram2.com/p/p0663/1.jpg"/ width="100px" height="100px">
        REJOBにあるコミュニティにどうしたら参加できるの？
        <br>
        「参加」ボタンから、参加表明をしよう！
        <br>
        <img alt="" src="http://pictogram2.com/p/p0742/1.png"/ width="100px" height="100px">
        コミュニティの活動記録を残したい！
        <br>
        コミュニティページで活動記録を投稿しよう！
        <br>
        <% if current_member.sign_in_count == 1 %>
        <a aria-controls="settings" data-toggle="tab" href="#settings" role="tab" class="btn btn-material-pink">次へ</a>
        <% else %>
        <%= link_to 'コミュニティを見に行く', communities_path, class:"btn btn-material-pink" %>
        <% end %>
      </div>
      <div class="tab-pane" id="settings" role="tabpanel">
        <h4>REJOBで開催されるイベントに参加できる！</h4>
        <br>
        <img alt="" src="http://pictogram2.com/p/p0986/1.png"/ width="100px" height="100px">
        リジョブの社員で飲み会をしよう！
        <br>
        <img alt="" src="http://pictogram2.com/p/p0663/1.jpg"/ width="100px" height="100px">
        リジョブでどんなイベントがあるのかな？
        <br>
        イベント一覧からイベントに「参加」しよう！
        <br>
        <img alt="" src="http://pictogram2.com/p/p0227/6.png"/ width="100px" height="100px">
        飲み会行きたい人いないかな？
        <br>
        気軽にイベントを作成して招待しよう！
        <br/>
        <% if current_member.sign_in_count == 1 %>
        <%= link_to 'はじめる', edit_member_path(current_member.id), class:"btn btn-material-pink" %>
        <% else %>
        <%= link_to 'REJOBの掲示板を見に行く', events_path, class:"btn btn-material-pink" %>
        <% end %>
      </div>
    </div>

  </div>

  <div class="form-group" style="text-align: center; margin-right: 4%">
    <% if current_member.sign_in_count > 1 %>
    <%= link_to 'top', top_page_home_path, class:"btn btn-material-pink" %>
    <% end %>
  </div>
</div>

app/views/home/welcome.html.erb
<body>
  <div id="main">
    <div class="row">
      <%= image_tag "rejoßook.png", class: "icon col-md-7 col-md-offset-3", alt: "アイコン", height: "150", width: "500"  %>
      <% if current_member == nil %>
      <%= link_to 'Start Rejoβook', new_member_session_path, class: "top btn btn-flat btn-material-pink col-xs-3 col-xs-offset-9"   %>
      <% else %>
      <%= link_to 'Start Rejoβook', my_page_home_path, class: "top btn btn-flat btn-material-pink col-xs-3 col-xs-offset-9"   %>
      <% end %>
    </div>
  </div>
</body>

<!--設定部分開始-->

<!-- Mobile support -->
<meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
<link href="css/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
<link href="css/roboto.min.css" rel="stylesheet">
<link href="css/material-fullpalette.min.css" rel="stylesheet">
<link href="css/material.min.css" rel="stylesheet">
<link href="css/ripples.min.css" rel="stylesheet">
<link href="css/roboto.min.css" rel="stylesheet">

<!-- Dropdown.js -->
<link href="css/jquery.dropdown.css" rel="stylesheet">

<!--ここからjsの設定部分-->
<script src="js/jquery-1.10.2.min.js"></script>
<script src="js/bootstrap.min.js"></script>

<script src="js/ripples.min.js"></script>
<script src="js/material.min.js"></script>
<script>
  $(document).ready(function () {
  // This command is used to initialize some elements and make them work properly
    $.material.init();
  });
</script>