config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'
  get 'chats/to_message'

  # RESTfulなURLを自動生成してくれるresources

  #基本ページ系のルーティング
  root to: 'home#top_page'
  resource :home, path: '',  only: [] do
    get 'welcome' => 'home#welcome', as: 'welcome'
    get 'my_page' => 'home#index',  as: 'my_page'
    get 'top_page' => 'home#top_page', as: 'top_page'
    get 'contact_list' => 'home#contact_list', as: 'contact_list'
    get 'tutorial' => 'home#tutorial', as: 'tutorial'
  end


  #user系のルーティング
  resources :members
  resources :events
  post 'events/add_member' => 'events#add_member', as: 'event_add_member'


  #member_messageのルーティング
  resources :member_messages


  #deviseのroutes設定
  devise_for :members, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }, controllers: {
    # membersのomniauth_callbackというコントローラにルーティングします
    omniauth_callbacks: "members/omniauth_callbacks"}

  #community系のルーティング
  resources :communities, except: [:add_member] do
  end
  post 'communities/add_member' => 'communities#add_member', as: 'community_add_member'
  #シャッフルコミュニティの生成
  get 'set_shuffle' => 'communities#set_shuffle', as: 'community_set_shuffle'
  post 'shuffle_community' => 'communities#shuffle_community', as: 'community_shuffle_communityr'

  resources :community_comments

  #about rejobook_news routing
  resources :news, controller: :rejobook_news
  post "news/create_news_comment" => 'rejobook_news#create_news_comment', as: 'create_news_comment'
  #get '*path', controller: 'application', action: 'render_404'

  #admin管理画面用のルーティング
  resource :admin_users, only: [] do
    get  'member_index',  to: 'admin_users#member_index'
    get  'community_index',  to: 'admin_users#community_index'
    get  'message_index',  to: 'admin_users#message_index'
    get  'news_index',  to: 'admin_users#news_index'
    get  'index',  to: 'admin_users#index'
  end

  #お問い合わせ用ルーティング
  get 'contact', to: 'contacts#contact'
  post 'contact/post_contact', to: 'contacts#post_contact'

  #resources :articles
  get 'articles/all_index'
  get 'articles/facebook_index'
  get 'articles/show'

  get 'news/delete_comment/:comment_id/:news_id' => 'rejobook_news#delete_comment'




=begin
  #thank_buttonのためのルーティング
  resources :thanks, only: []
  get 'members/:id/thanks/:from_member_id/thank_create' => 'thanks#thank_create'
=end

=begin
  devise_for :members, path: 'member', except: [:session] do
    get 'login', to: 'devise/sessions#new', as:  'login'
    post 'login', to: 'devise/sessions#create', as:  'login'
    match 'logout', to: 'devise/sessions#destroy', as:  'logout',
    controllers: {
    # membersのomniauth_callbackというコントローラにルーティングします
      omniauth_callbacks: "members/omniauth_callbacks"
    }
  end
=end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :community
  belongs_to :member
  # membersテーブルとeventsテーブルをつなぐ
  has_many :members_events
  has_many :members, through: :members_events


  has_attached_file :image,
                    styles: {medium: '640x160>'}, # size
                    url: '/system/images/members/:basename.:extension', # 画像保存先のURL先
                    path: "#{Rails.root}/public/system/images/members/:basename.:extension" # サーバ上の画像保存先パス

  scope :available, -> { where('event_day >= ? OR event_day IS NULL', Time.zone.today).order('event_day desc') }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include Chatwork
  before_action :require_login!
  before_action :require_admin_login!, only: [:destroy]
=begin
after_action :reset_session_count!
after_action :reset_home_session, only: [:index]
=end

  def index
    @events = Event.available.page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    if  @event.members.exists?(current_member)
      @join_member = current_member
    else
      @join_member = nil
    end
  end


  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      # 34886078は全体のルームid
      Chatwork.post_chatwork('34203917', @event)
      redirect_to event_path(@event)
    else
      flash[:error] = '未入力の項目があります'
      redirect_to new_event_path
    end
  end

  def edit
    @event =  Event.find(params[:id])

    unless @event.member_id == current_member.id || current_member.admin?
      flash[:error] = 'イベント作成者ではないため、編集できません'
      redirect_to events_path
    end

  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to events_path
  end

  def add_member
    join_event = params[:event][:event_id]
    add_member = params[:event][:add_member_id]

    @find_event = MembersEvent.where(event_id: join_event)
    if @find_event.where(member_id: add_member).present?
      MembersEvent.where(event_id: join_event, member_id: add_member).destroy_all
    else
      MembersEvent.create(event_id: join_event, member_id: add_member)
    end
    redirect_to event_path(join_event)
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :event_day, :image, :event_id, :community_id, :member_id, member_ids: [])
  end

  def reset_session_count!
    reset_count(Event)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_data.html.erb
<meta charset="UTF-8">

<!-- Mobile support -->
<meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
<link href="dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
<link href="dist/css/roboto.min.css" rel="stylesheet">
<link href="dist/css/material-fullpalette.min.css" rel="stylesheet">
<link href="dist/css/ripples.min.css" rel="stylesheet">

<!-- Dropdown.js -->
<link href="dist/css/jquery.dropdown.css" rel="stylesheet">

<body>
  <div class="container">
    <div class="panel-head panel panel-default">
      <div class="panel-body">

        <div class="event_form row">

          <div class="form-group">
            <h2 style="text-align: center">
              <%= @event.name %>
            </h2>
          </div>

          <div class="form-group">
            <div class="form-group">
              開催日時
            <%= @event.event_day.strftime("%y年 %m月 %d日") if @event.event_day.present?  %>
            </div>
            <% if @event.community.present? %>
            <div class="form-group">
              <P><%= link_to @event.community.name, community_path(@event.community.id) %>開催のイベントです</p>
            </div>
            <% end %>
          </div>

          <div class="form-group" style="text-align: center">
            <p><%= @event.try(:description) %></p>
          </div>

          <div class="event_members" style="margin-buttom:50px;">
            <p>
              イベント参加者
            </p>
<!--参加者の社員個別ページのプロフィール写真が反映-->
            <ul style="list-style: none;">
              <% @event.members.each do |member| %>
              <li style="float: left">
                <%= link_to image_tag( member.image.url, :size => "50x50"), member_path(member.id) %><br>
              </li>
              <% end %>
            </ul><br>
          </div>

          <div class="form-group" style="margin-top: 50px;" >
            <!--見ているコミュニティへの参加不参加-->
                        <%= form_for(:event, url: event_add_member_path) do |f| %>
                        <%= f.hidden_field 'event_id', :value => params[:id] %>
                        <%= f.hidden_field 'add_member_id', :value => current_member.id %>
                        <%= f.submit @join_member.present?  ? '参加を取りけす' : '参加', class: 'btn btn-material-pink' %>
            <a href="https://chouseisan.com/" class="btn btn-material-pink" target=”_blank”>日程を調整する</a>

            <%= link_to '編集', edit_event_path(@event), class: 'btn btn-material-grey'  if @event.member = current_member %>

                        <% end %>
          </div>

        </div>

      </div>
    </div>
  </div>
</body>

app/views/events/_form.html.erb
<head>
  <meta charset="UTF-8">

<!-- Mobile support -->
  <meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
  <link href="stylesheets/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
  <link href="stylesheets/roboto.min.css" rel="stylesheet">
  <link href="stylesheets/material-fullpalette.min.css" rel="stylesheet">
  <link href="stylesheets/ripples.min.css" rel="stylesheet">

<!-- Dropdown.js -->
  <link href="stylesheets/jquery.dropdown.css" rel="stylesheet">
</head>

<body>
  <%= form_for @event do |f| %>
  <div class="container">
    <div class="panel-head panel-body panel panel-default">
        <div class="row" style="margin-left: 3%">

          <div class="form-group">
            <%= f.label  'イベント名', class: "col-md-3 col-xs-3 control-label"  %>
            <div class="col-md-9 col-xs-9">
              <%= f.text_field :name, class: "input", placeholder: "例：○○決起会！など"  %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label 'イベントの説明', class: "col-md-3 col-xs-3 control-label" %>
            <div class="col-md-9 col-xs-9">
              <%= f.text_area :description, class: "input", placeholder: "例:○○が有名なお店にいきましょう！参加〆切は○日まで！など", rows: "3"  %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :event_day, '開催日', class: "col-md-3 col-xs-3 control-label" %>
            <div class="col-md-9 col-xs-9">
            <%= f.date_select :event_day, use_month_numbers:"true", default:"", :include_blank => true, :start_year => 2015, class: 'col-md-8 col-xs-8 input'  %>
            </div>
          </div>
          <%= f.hidden_field 'member_id', :value => current_member.id %>

          <div class="form-group">
       <a href="https://chouseisan.com/" class="btn btn-material-pink" target=”_blank”>日程を調整する</a>
     </div>


          <div class="form-group">
            <div class="col-md-3 col-xs-3 control-label" style="font-weight: bold;">イベントに社員を招待する</div>
            <div class="col-md-12 co-xs-3" style="margin-top: 1%">
          <% Member.all.each_with_index do |member, idx| %>
              <input value=<%= member.id %> name="event[member_ids][]" id="event_member_ids_<%= member.id %>" type="checkbox"
              <% if MembersEvent.where(event_id: params[:id]).pluck(:member_id).include?(member.id) %>
              checked="checked"
              <% end %>
              >
              <label for="event_member_ids_<%= member.id %>" style="margin-right: 10px;"><%= member.name %></label>
              <% if idx == 7 %>
              <br>
              <% end %>
          <% end %>
           </div>
          </div>
          <% if  params[:format].present?  %>
            <%= f.hidden_field 'community_id', :value => params[:format]  %>
          <% end %>
          <div class="form-group">
            <%= f.submit "保存", class: "btn btn-material-pink" %>
            <input class="btn btn-material-grey" type="reset" value="リセット">
            <%= link_to 'キャンセル', events_path, class:"btn btn-material-grey" %>
          </div>
        </div>
    </div>
  </div>
  <% end %>
</body>

<!--設定部分開始-->

<!-- Mobile support -->
<meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
<link href="stylesheets/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
<link href="stylesheets/roboto.min.css" rel="stylesheet">
<link href="stylesheets/material-fullpalette.min.css" rel="stylesheet">
<link href="stylesheets/material.min.css" rel="stylesheet">
<link href="stylesheets/ripples.min.css" rel="stylesheet">

<!-- Dropdown.js -->
<link href="stylesheets/jquery.dropdown.css" rel="stylesheet">

<!--ここからjsの設定部分-->
<script src="javascript/jquery-1.10.2.min.js"></script>
<script src="javascript/bootstrap.min.js"></script>

<script src="javascript/ripples.min.js"></script>
<script src="javascript/material.min.js"></script>
<script>
$(document).ready(function () {
// This command is used to initialize some elements and make them work properly
  $.material.init();
});
</script>

app/views/events/edit.html.erb
<%= render template: 'layouts/_nav_bar' %>

<%= render 'form' %>

app/views/events/index.html.erb
<head>
  <meta charset="UTF-8">

<!-- Mobile support -->
  <meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
  <link href="dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
  <link href="dist/css/roboto.min.css" rel="stylesheet">
  <link href="dist/css/material-fullpalette.min.css" rel="stylesheet">
  <link href="dist/css/ripples.min.css" rel="stylesheet">

<!-- Dropdown.js -->
  <link href="dist/css/jquery.dropdown.css" rel="stylesheet">
</head>
<%= render template: 'layouts/_nav_bar' %>

<body>
  <div class="container">
    <div class="form-group">
        <%= link_to '新規イベント作成', new_event_path, class: "btn btn-material-pink" %>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="icon-preview">
          <i class="mdi-social-mood"></i>
          <span>&nbsp;イベント一覧</span>
        </div>
        <div class="row">
            <% @events.each_with_index do |event, idx| %>
            <div class="event_index panel panel-default">
              <div class="panel-heading">
                <%= link_to event.name, event_path(event.id) %>
                <%= event.event_day.strftime("%y年 %m月 %d日") if event.event_day.present?  %>
              </div>

              <div class="event_show" style="margin-left: 2%; margin-top: 1%">
                <%= truncate("#{event.description}", :omission => "・・・", length: 23) if event.description.present? %>
                <br>
                <p>イベント作成者
                <br><%= link_to event.member.name, member_path(event.member.id) %></p>
                <br>イベント参加人数<br>
                <%= event.members.count %>人 <br>
                <div class="form-group">
                  <%= link_to '編集', edit_event_path(event.id), class: 'btn btn-material-grey'  if event.member_id = current_member.id %>
                </div>
              </div>
            </div>
          <div class="form-group">
          </div>
            <% end %>
        </div>
        <div style="text-align:center">
          <%= paginate(@events) %>
        </div>

      </div>
    </div>
  </div>
</body>

app/views/events/new.html.erb
<%= render template: 'layouts/_nav_bar' %>

<%= render 'form' %>

app/views/events/show.html.erb
<%= render template: 'layouts/_nav_bar' %>

<%= render 'event_data' %>