config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'
  get 'chats/to_message'

  # RESTfulなURLを自動生成してくれるresources

  #基本ページ系のルーティング
  root to: 'home#top_page'
  resource :home, path: '',  only: [] do
    get 'welcome' => 'home#welcome', as: 'welcome'
    get 'my_page' => 'home#index',  as: 'my_page'
    get 'top_page' => 'home#top_page', as: 'top_page'
    get 'contact_list' => 'home#contact_list', as: 'contact_list'
    get 'tutorial' => 'home#tutorial', as: 'tutorial'
  end


  #user系のルーティング
  resources :members
  resources :events
  post 'events/add_member' => 'events#add_member', as: 'event_add_member'


  #member_messageのルーティング
  resources :member_messages


  #deviseのroutes設定
  devise_for :members, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }, controllers: {
    # membersのomniauth_callbackというコントローラにルーティングします
    omniauth_callbacks: "members/omniauth_callbacks"}

  #community系のルーティング
  resources :communities, except: [:add_member] do
  end
  post 'communities/add_member' => 'communities#add_member', as: 'community_add_member'
  #シャッフルコミュニティの生成
  get 'set_shuffle' => 'communities#set_shuffle', as: 'community_set_shuffle'
  post 'shuffle_community' => 'communities#shuffle_community', as: 'community_shuffle_communityr'

  resources :community_comments

  #about rejobook_news routing
  resources :news, controller: :rejobook_news
  post "news/create_news_comment" => 'rejobook_news#create_news_comment', as: 'create_news_comment'
  #get '*path', controller: 'application', action: 'render_404'

  #admin管理画面用のルーティング
  resource :admin_users, only: [] do
    get  'member_index',  to: 'admin_users#member_index'
    get  'community_index',  to: 'admin_users#community_index'
    get  'message_index',  to: 'admin_users#message_index'
    get  'news_index',  to: 'admin_users#news_index'
    get  'index',  to: 'admin_users#index'
  end

  #お問い合わせ用ルーティング
  get 'contact', to: 'contacts#contact'
  post 'contact/post_contact', to: 'contacts#post_contact'

  #resources :articles
  get 'articles/all_index'
  get 'articles/facebook_index'
  get 'articles/show'

  get 'news/delete_comment/:comment_id/:news_id' => 'rejobook_news#delete_comment'




=begin
  #thank_buttonのためのルーティング
  resources :thanks, only: []
  get 'members/:id/thanks/:from_member_id/thank_create' => 'thanks#thank_create'
=end

=begin
  devise_for :members, path: 'member', except: [:session] do
    get 'login', to: 'devise/sessions#new', as:  'login'
    post 'login', to: 'devise/sessions#create', as:  'login'
    match 'logout', to: 'devise/sessions#destroy', as:  'logout',
    controllers: {
    # membersのomniauth_callbackというコントローラにルーティングします
      omniauth_callbacks: "members/omniauth_callbacks"
    }
  end
=end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

  before_save :create_admin
  validates :password, presence: true

  def correct_password?(input_password)
    self.password == Digest::MD5.hexdigest(input_password).to_s
  end

  def create_admin
    hashed_password = Digest::MD5.hexdigest(self.password).to_s
    self.password = hashed_password
  end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  # before_action :require_login!
  # before_action :require_admin_login!
  http_basic_authenticate_with name: 'rejobook', password: 'adminlogin'

  def index

  end

  def member_index
    if params[:q].nil?
      @search = Member.none.search
      @results = Member.all
    else
      @search = Member.search(params[:q])
      @results = @search.result(distinct: true)
    end
  end

  def community_index
    @communities = Community.all
  end

  def message_index
    @messages = MemberMessage.all
  end

  def news_index
    @news = News.all
  end


  def member_destroy

  end

  def community_destroy

  end

  def message_destroy

  end

  def news_destroy

  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/community_index.html.erb
<%= render template: 'layouts/_nav_bar' %>
<div class="container">
  <div class="panel panel-default">
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th>No</th>
                <th>コミュニティ名</th>
                <th>活動内容</th>
            </tr>
        </thead>
        <tbody>
          <% @communities.each_with_index do |community, idx| %>
            <% if idx % 2 == 0 %>
            <tr class="success">
            <% else %>
            <tr>
            <% end %>
                <td><%= community.id %></td>
                <td><%= community.name %></td>
                <td><%= community.description %></td>
                <td><%= link_to '詳細', community_path(community.id) %></td>
                <td><%= link_to '削除', community_path(community.id) %></td>
            </tr>
            <% end %>
          </tbody>
    </table>
  </div>
</div>

app/views/admin_users/index.html.erb
<h4>管理者ページ一覧</h4>
<%= link_to 'メンバー', member_index_admin_users_path %>
<%= link_to 'コミュニティ', community_index_admin_users_path %>
<%= link_to '掲示版', news_index_admin_users_path %>

app/views/admin_users/member_index.html.erb
<%= render template: 'layouts/_nav_bar' %>
<div class="container">
    <%= search_form_for @search, url: member_index_admin_users_path(params[:q]) do |f| %>
    <div class="searchitem row">
      <div class="form-group col-md-6 col-xs-6">
        <%= f.label :name_or_kana_cont, '名前', class: "control-label" %>
        <% if params[:q].present? %>
        <% if params[:q][:name_or_kana_cont].present? %>
        <%= f.search_field :name_or_kana_cont, :placeholder => "#{params[:q][:name_or_kana_cont]}", rows: "3" %>
        <% else %>
        <%= f.search_field :name_or_kana_cont, class: "search_name", placeholder: "検索する名前を入力してください", rows: "3" %>
        <% end %>
        <% else %>
        <%= f.search_field :name_or_kana_cont, class: "search_name", placeholder: "検索する名前を入力してください", rows: "3" %>
        <% end %>
      </div>
      <div class="form-group col-md-6 col-xs-6" style="text-align: center">
        <%= f.label :department, '所属部署' %>
        <br>
        <% if params[:q].present? %>
        <% if params[:q][:departments_id_in].present? %>
        <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :selected => params[:q][:departments_id_in], :include_blank => true %>
        <% else %>
        <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :prompt => "部署を選択してください" %>
        <% end %>
        <% else %>
        <%= collection_select :q, :departments_id_in, Department.all, :id, :name, :prompt => "部署を選択してください" %>
        <% end %>
      </div>
    </div>

    <div class="form-group search">
      <%= f.submit "社員を表示", class: "btn btn-material-pink"%>
    </div>
    <% end %>
<!--ここに検索結果をだす→テーブルで-->
    <h4 class="result">検索結果</h4>
    <div class="panel panel-default">
    表示人数:  <%= @results.count %>人
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>No</th>
            <th>名前</th>
            <th>チャットワークid</th>
            <th>内線番号</th>
          </tr>
        </thead>
        <tbody>
          <% @results.each_with_index do |result, idx| %>
          <% if idx % 2 == 0 %>
          <tr class="success">
            <% else %>
            <tr>
              <% end %>
              <td><%= result.id %></td>
              <td><%= result.name %></td>
              <td><%= result. chatwork_id%></td>
              <td><%= result.indoor_call %></td>
              <td><%= link_to '詳細', member_path(result.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <style media="screen">
      th {
        text-align: center;
      }
    </style>

</div>

app/views/admin_users/message_index.html.erb
<%= render template: 'layouts/_nav_bar' %>
<div class="container">
  <div class="panel panel-default">
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th>No</th>
                <th>メッセージ内容</th>
                <th>発信者</th>
                <th>受信者</th>
            </tr>
        </thead>
        <tbody>
          <% @messages.each_with_index do |message, idx| %>
            <% if idx % 2 == 0 %>
            <tr class="success">
            <% else %>
            <tr>
            <% end %>
                <td><%= message.id %></td>
                <td><%= message.message %></td>
                <td><%= Member.find(message.from_member_id).name %></td>
                <td><%= Member.find(message.to_member_id).name %></td>
                <td><%= link_to '詳細', member_path(message.to_member_id) %></td>
                <td><%= link_to '削除', member_path(message.to_member_id) %></td>
            </tr>
            <% end %>
          </tbody>
    </table>
  </div>
</div>

app/views/admin_users/news_index.html.erb
<%= render template: 'layouts/_nav_bar' %>
<div class="container">
  <div class="panel panel-default">
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th>No</th>
                <th>タイトル</th>
                <th>内容</th>
                <th>メンバー情報</th>
            </tr>
        </thead>
        <tbody>
          <% @news.each_with_index do |news, idx| %>
            <% if idx % 2 == 0 %>
            <tr class="success">
            <% else %>
            <tr>
            <% end %>
                <td><%= news.id %></td>
                <td><%= news.title %></td>
                <td><%= news.content %></td>
                <td><%= news.member_id %></td>
                <td><%= link_to '詳細', news_path(news.id) %></td>
                <td><%= link_to '削除', news_path(news.id) %></td>
            </tr>
            <% end %>
          </tbody>
    </table>
  </div>
</div>