config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'
  get 'chats/to_message'

  # RESTfulなURLを自動生成してくれるresources

  #基本ページ系のルーティング
  root to: 'home#top_page'
  resource :home, path: '',  only: [] do
    get 'welcome' => 'home#welcome', as: 'welcome'
    get 'my_page' => 'home#index',  as: 'my_page'
    get 'top_page' => 'home#top_page', as: 'top_page'
    get 'contact_list' => 'home#contact_list', as: 'contact_list'
    get 'tutorial' => 'home#tutorial', as: 'tutorial'
  end


  #user系のルーティング
  resources :members
  resources :events
  post 'events/add_member' => 'events#add_member', as: 'event_add_member'


  #member_messageのルーティング
  resources :member_messages


  #deviseのroutes設定
  devise_for :members, path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }, controllers: {
    # membersのomniauth_callbackというコントローラにルーティングします
    omniauth_callbacks: "members/omniauth_callbacks"}

  #community系のルーティング
  resources :communities, except: [:add_member] do
  end
  post 'communities/add_member' => 'communities#add_member', as: 'community_add_member'
  #シャッフルコミュニティの生成
  get 'set_shuffle' => 'communities#set_shuffle', as: 'community_set_shuffle'
  post 'shuffle_community' => 'communities#shuffle_community', as: 'community_shuffle_communityr'

  resources :community_comments

  #about rejobook_news routing
  resources :news, controller: :rejobook_news
  post "news/create_news_comment" => 'rejobook_news#create_news_comment', as: 'create_news_comment'
  #get '*path', controller: 'application', action: 'render_404'

  #admin管理画面用のルーティング
  resource :admin_users, only: [] do
    get  'member_index',  to: 'admin_users#member_index'
    get  'community_index',  to: 'admin_users#community_index'
    get  'message_index',  to: 'admin_users#message_index'
    get  'news_index',  to: 'admin_users#news_index'
    get  'index',  to: 'admin_users#index'
  end

  #お問い合わせ用ルーティング
  get 'contact', to: 'contacts#contact'
  post 'contact/post_contact', to: 'contacts#post_contact'

  #resources :articles
  get 'articles/all_index'
  get 'articles/facebook_index'
  get 'articles/show'

  get 'news/delete_comment/:comment_id/:news_id' => 'rejobook_news#delete_comment'




=begin
  #thank_buttonのためのルーティング
  resources :thanks, only: []
  get 'members/:id/thanks/:from_member_id/thank_create' => 'thanks#thank_create'
=end

=begin
  devise_for :members, path: 'member', except: [:session] do
    get 'login', to: 'devise/sessions#new', as:  'login'
    post 'login', to: 'devise/sessions#create', as:  'login'
    match 'logout', to: 'devise/sessions#destroy', as:  'logout',
    controllers: {
    # membersのomniauth_callbackというコントローラにルーティングします
      omniauth_callbacks: "members/omniauth_callbacks"
    }
  end
=end
end

app/models/community.rb
class Community < ActiveRecord::Base
  # 検索条件について
  scope :latest_community, ->  (limit = 5) { order(created_at: :desc).limit(limit) }

  # 自分が所属しているコミュニティの情報
  scope :my_communities, -> (login) { where(member_id: login.id) }

  has_many :community_comments
  belongs_to :member

  # communitiesテーブルとmembersテーブルをつなぐ
  has_many :members_communities
  has_many :members, through: :members_communities



  # communityのvalidation
  # attr_accessor :image_file_name, :image_content_type, :image_file_size, :image_updated_at

  validates :name, presence: true
  validates :description, presence: true

  has_attached_file :image,
                    styles: {medium: '640x160>'}, # size
                    url: '/system/images/communities/:basename.:extension', # 画像保存先のURL先
                    path: "#{Rails.root}/public/system/images/communities/:basename.:extension" # サーバ上の画像保存先パス


  # 拡張子のvalidationチェック
  # validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"], presence: true

  do_not_validate_attachment_file_type :image

  def shuffle_community(member_ids)
    Communiy.create


  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :community
  belongs_to :member
  # membersテーブルとeventsテーブルをつなぐ
  has_many :members_events
  has_many :members, through: :members_events


  has_attached_file :image,
                    styles: {medium: '640x160>'}, # size
                    url: '/system/images/members/:basename.:extension', # 画像保存先のURL先
                    path: "#{Rails.root}/public/system/images/members/:basename.:extension" # サーバ上の画像保存先パス

  scope :available, -> { where('event_day >= ? OR event_day IS NULL', Time.zone.today).order('event_day desc') }

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  include Chatwork
  before_action :require_login!
  before_action :require_admin_login!, only: [:destroy]
  after_action :reset_session_count!
  after_action :reset_home_session, only: [:index]

  def index
    @communities = Community.all.page(params[:page])
  end

  def show
    @community = Community.find(params[:id])
    @comment = CommunityComment.new

    if  @community.members.exists?(current_member)
      @join_member = current_member
    else
      @join_member = nil
    end
  end


  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    @community.member_id = current_member.id
    if @community.save
      # 34886078は全体のルームid
      Chatwork.post_chatwork('34203917', @community)
      redirect_to community_path(@community)
    else
      flash[:error] = '未入力の項目があります'
      redirect_to new_community_path
    end
  end

  def edit
    @community =  Community.find(params[:id])

    unless @community.member_id == current_member.id || current_member.admin?
      flash[:error] = 'コミュニティ管理者でないため編集できません'
      redirect_to communities_path
    end

  end

  def update
    @community = Community.find(params[:id])
    @community.update_attributes(community_params)
    redirect_to community_path(@community)
  end

  def destroy
    Community.find(params[:id]).destroy
    redirect_to communities_path
  end

  def add_member
    join_community = params[:community][:community_id]
    add_member = params[:community][:add_member_id]

    @find_community = MembersCommunity.where(community_id: join_community)
    if @find_community.where(member_id: add_member).present?
      MembersCommunity.where(community_id: join_community, member_id: add_member).destroy_all
    else
      MembersCommunity.create(community_id: join_community, member_id: add_member)
    end
    redirect_to community_path(join_community)
  end

  def set_shuffle
  end

  def shuffle_community
    # member_ids = params
    @community = Community.new
    @community.name = params[:name]
    @community.description = params[:name]
    @community.member_id = current_member.id
    if @community.save
      Chatwork.post_chatwork('34203917', @community)
      # ここに検索の条件ありなしのif分
      numbers = params[:numbers].to_i
      member_ids = Member.pluck(:id).sample(numbers)
      member_ids.size.times do |number|
        member_communiy = MembersCommunity.new
        member_communiy.community_id = @community.id
        member_communiy.member_id = member_ids[number]
        member_communiy.save
      end
      redirect_to community_path(@community.id)
    else
      flash[:error] = 'have error'
      redirect_to communities_path
    end
  end

  private

  def community_params
    params.require(:community).permit(:name, :description, :image, member_ids: [])
  end

  def reset_session_count!
    reset_count(Community)
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community_comments.html.erb
<%= form_for @comment do |f|  %>
<div class="communitypost row breadcrumb">
  <div class="form-group">
    <%= f.label :comment, 'コメント投稿', class: "col-md-2 col-xs-2 control-label" %>
    <div class="col-md-10 col-xs-10">
      <%= f.text_area :comment, class: "input", placeholder: "投稿内容を入力してください", rows: "3"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, '写真投稿', class: "col-md-2 col-xs-2 control-label" %>
    <div class="uploadButton">
      ファイルを選択
      <input onchange="uv.style.display='inline-block'; uv.value = this.value;" type="file"/>
      <input class="uploadValue" disabled id="uv" type="text"/>
      <%= f.file_field :image %>
    </div>
  </div>
</div>
    <%= f.hidden_field 'community_id', :value => params[:id] %>
    <%= f.submit '投稿', class: 'btn btn-material-pink' %>
    <input class="btn btn-material-grey" type="reset" value="キャンセル">
  <% end %>

app/views/communities/_community_data.html.erb
<meta charset="UTF-8">

<!-- Mobile support -->
<meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
<link href="dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
<link href="dist/css/roboto.min.css" rel="stylesheet">
<link href="dist/css/material-fullpalette.min.css" rel="stylesheet">
<link href="dist/css/ripples.min.css" rel="stylesheet">

<!-- Dropdown.js -->
<link href="dist/css/jquery.dropdown.css" rel="stylesheet">

<body>
  <div class="container">
    <div class="panel-head panel panel-default">
      <div class="panel-body">

        <div class="community_form row">
          <div class="form-group">
            <h2 style="text-align: center">
              <%= @community.name %>
            </h2>
          </div>

          <div class="communityimage">
            <%= image_tag @community.image.url  %>
<!--コミュニティ画像表示部分-->
          </div>

            <div class="form-group">
              <p style="font-weight: bold"><%= @community.try(:description) %></p>
            </div>
          <div class="community_members col-md-12 col-xs-12">
            <p>
              コミュニティ管理者；<%= link_to @community.member.name, member_path(@community.member.id) if @community.member.present? %>
            </p>
<!--参加者の社員個別ページのプロフィール写真が反映-->
          </div>

          <div class="community_members col-md-12 col-xs-12">
            <p>
              コミュニティ参加者
            </p>
<!--参加者の社員個別ページのプロフィール写真が反映-->
            <ul style="list-style: none;">

              <% @community.members.each do |member| %>
              <li style="float: left">
                <%= link_to image_tag( member.image.url, :size => "50x50"), member_path(member.id) %><br>
              </li>
              <% end %>
            </ul><br>
          </div>

          <div class="form-group col-md-12 col-xs-12">

<!--見ているコミュニティへの参加不参加-->
            <%= form_for(:community, url: community_add_member_path) do |f| %>
            <%= f.hidden_field 'community_id', :value => params[:id] %>
            <%= f.hidden_field 'add_member_id', :value => current_member.id %>
            <br>
            <%= f.submit @join_member.present?  ? '参加を取りけす' : '参加', class: 'btn btn-material-pink' %>
            <% end %>
            <div class="form-group">
              <%= link_to 'イベントを作成する', new_event_path(params[:community_id] = @community.id ), class:"btn btn-material-pink" %>
            </div>
          <div class="form-group">
            <%= render 'community_comments' %>
          </div>

          </div>



        <% @community.community_comments.reverse_each do |comment| %>
          <div class="comments">
            <div class="form-group">
              <div class="coments_pic col-lg-2">
<!--投稿者の社員個別ページのプロフィール写真が反映-->
                <%= link_to image_tag(comment.member.image.url, :size => "50x50"), member_path(comment.member.id) %>
                <br/><%= link_to "#{comment.member.name}", member_path(comment.member.id) %>
<!--名前はどうする？-->
              </div>
              <div class="col-lg-10">
                <%= comment.comment %>
                <%= comment.created_at.strftime("%Y/%m/%d %H:%M") %>
              </div>
              <div class="col-lg-12" style="text-align: center">
                <%= image_tag comment.image.url, :size => "250x100" if comment.image_file_name.present?  %>
              </div>
            </div>
          </div>
        <% end %>

          <div class="form-group">
              <%= link_to '編集', edit_community_path(@community), class: 'btn btn-material-grey'  if @join_member.present? || current_member.admin? %>
          </div>
        </div>

      </div>
    </div>
  </div>
</body>

app/views/communities/_form.html.erb
<head>
  <meta charset="UTF-8">

<!-- Mobile support -->
  <meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
  <link href="stylesheets/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
  <link href="stylesheets/roboto.min.css" rel="stylesheet">
  <link href="stylesheets/material-fullpalette.min.css" rel="stylesheet">
  <link href="stylesheets/ripples.min.css" rel="stylesheet">

<!-- Dropdown.js -->
  <link href="stylesheets/jquery.dropdown.css" rel="stylesheet">
</head>

<body>
  <%= form_for @community do |f| %>
  <div class="container">
    <div class="panel-head panel panel-default">
      <div class="panel-body">

        <div class="community_form row">
          <div class="form-group">
            <label class="col-lg-3 control-label" for="inputFile">コミュニティ画像</label>
            <div class="uploadButton">
              ファイルを選択
              <input onchange="uv.style.display='inline-block'; uv.value = this.value;" type="file"/>
              <input class="uploadValue" disabled id="uv" type="text"/>
              <%= f.file_field :image %>
              
            </div>
          </div>

          <div class="form-group">
            <%= f.label  'コミュニティ名', class: "col-md-3 col-xs-3 control-label"  %>
            <div class="col-md-9 col-xs-9">
              <%= f.text_field :name, class: "input", placeholder: "コミュニティの名前を入力してください"  %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label 'コミュニティの説明', class: "col-md-3 col-xs-3 control-label" %>
            <div class="col-md-9 col-xs-9">
              <%= f.text_area :description, class: "input", placeholder: "コミュニティの説明を入力してください", rows: "3"  %>
            </div>
          </div>

          <div class="form-group">
          <% Member.all.each_with_index do |member, idx| %>
              <input value=<%= member.id %> name="community[member_ids][]" id="community_member_ids_<%= member.id %>" type="checkbox"
              <% if MembersCommunity.where(community_id: params[:id]).pluck(:member_id).include?(member.id) %>
              checked="checked"
              <% end %>
              >
              <label for="community_member_ids_<%= member.id %>" style="margin-right: 10px;"><%= member.name %></label>
              <% if idx == 7 %>
              <br>
              <% end %>
          <% end %>
          </div>

          <div class="form-group">
            <%= f.submit "保存", class: "btn btn-material-pink" %>
            <input class="btn btn-material-grey" type="reset" value="リセット">
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</body>

<!--設定部分開始-->

<!-- Mobile support -->
<meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
<link href="stylesheets/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
<link href="stylesheets/roboto.min.css" rel="stylesheet">
<link href="stylesheets/material-fullpalette.min.css" rel="stylesheet">
<link href="stylesheets/material.min.css" rel="stylesheet">
<link href="stylesheets/ripples.min.css" rel="stylesheet">

<!-- Dropdown.js -->
<link href="stylesheets/jquery.dropdown.css" rel="stylesheet">

<!--ここからjsの設定部分-->
<script src="javascript/jquery-1.10.2.min.js"></script>
<script src="javascript/bootstrap.min.js"></script>

<script src="javascript/ripples.min.js"></script>
<script src="javascript/material.min.js"></script>
<script>
$(document).ready(function () {
// This command is used to initialize some elements and make them work properly
  $.material.init();
});
</script>

app/views/communities/edit.html.erb
<%= render template: 'layouts/_nav_bar' %>

<%= render 'form' %>

app/views/communities/index.html.erb
<head>
  <meta charset="UTF-8">

<!-- Mobile support -->
  <meta content="width=device-width, initial-scale=1" name="viewport">

<!-- Twitter Bootstrap -->
  <link href="dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Material Design for Bootstrap -->
  <link href="dist/css/roboto.min.css" rel="stylesheet">
  <link href="dist/css/material-fullpalette.min.css" rel="stylesheet">
  <link href="dist/css/ripples.min.css" rel="stylesheet">

<!-- Dropdown.js -->
  <link href="dist/css/jquery.dropdown.css" rel="stylesheet">
</head>
<%= render template: 'layouts/_nav_bar' %>

<body>
  <div class="container">
    <div class="form-group">
        <%= link_to '新規コミュニティ作成', new_community_path, class: "btn btn-material-pink" %>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="icon-preview">
          <i class="mdi-social-group"></i>
          <span>&nbsp;コミュニティ一覧</span>
        </div>
        <div class="row">
            <% @communities.each_with_index do |community, idx| %>
            <div class="community_index panel" style="margin-right: 16px;">
              <div class="panel-heading"><%= link_to "#{community.name}", community_path(community.id) %></div>
              <div class="community_show panel-body">
                <%= link_to image_tag(community.image.url), community_path(community.id) %><br>
                <%= truncate("#{community.description}", :omission => "・・・", length: 23) if community.description.present? %>
                <br>
                <br>コミュニティ参加者<br>
                <%= community.members.count %>人
              </div>
            </div>
            <% end %>
        </div>
        <div style="text-align:center">
          <%= paginate(@communities) %>
        </div>

      </div>
    </div>
  </div>
</body>

app/views/communities/new.html.erb
<%= render template: 'layouts/_nav_bar' %>

<%= render 'form' %>

app/views/communities/set_shuffle.html.erb
<%= render template: 'layouts/_nav_bar' %>

<div class="container">
  <div class="panel panel-head panel-body panel-default">
    <div class="icon-preview">
      <i class="mdi-action-help"></i>
      <span>シャッフルコミュニティ作成
        <br>
        <br>
        ※ランダムに社員を選択し、コミュニティを作成します
      </span>
    </div>

    <form action="/shuffle_community" class="form-horizontal" method="post">
      <div class="row" style="margin-left: 3%">
        <div class="form-group">
          <label>コミュニティ名</label>
          <input type="text"  class="input col-md-8 col-xs-8" name="name" placeholder="例:きっかけ委員会　など" rows="3">
        </div>
        <div class="form-group">
          <label>コミュニティ説明</label>
          <textarea class="input col-md-8 col-xs-8" name="numbers" placeholder="例:今月のきっかけ委員会のグループです！など" rows="3"></textarea>
        </div>
        <div class="form-group">
          <label>1コミュニティの社員の人数を選択する</label>
          <input type="number" name="numbers"  value="0">
        </div>
      </div>

      <div class="form-group" style="margin-left: 3%">
        <input class="btn btn-material-pink" type="submit" value="シャッフル作成">
        <input class="btn btn-material-grey" type="reset" value="リセット">
      </div>
    </form>
  </div>
</div>

app/views/communities/show.html.erb
<%= render template: 'layouts/_nav_bar' %>

<%= render 'community_data' %>